// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpuqwwhmncowgfpmcvln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwdXF3d2htbmNvd2dmcG1jdmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5NTA3NzUsImV4cCI6MjA5MTUyNjc3NX0.ekGx4jMmr0nXlJ6DNTWCDC6xzLiDunWLQS38vIdIWKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});